#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($CHILD_STATUS.exitstatus) unless system "umask 002 && #{cmd}"
end

run 'foreman run bundle install --deployment --without development:test'

tasks = []
num_migrations = `git diff #{oldrev} #{newrev} --diff-filter=A --name-only -z db/migrate`.split("\0").size
tasks << 'db:migrate' if num_migrations > 0

run "foreman run bundle exec rake #{tasks.join(' ')}" if tasks.any?
